Base de datos general

In [3]:

import pandas as pd

df_Familias_En_Accion = pd.read_csv("C:/Users/migue/Music/MINTIC/mintic/modulo1/fuente de datos/Beneficiarios_M_s_Familias_en_Acci_n_20240914.csv")	
df_Familias_En_Accion

,Bancarizado,CodigoDepartamentoAtencion,CodigoMunicipioAtencion,Discapacidad,EstadoBeneficiario,Etnia,FechaInscripcionBeneficiario,Genero,NivelEscolaridad,NombreDepartamentoAtencion,...,TipoAsignacionBeneficio,TipoBeneficio,TipoDocumento,TipoPoblacion,RangoBeneficioConsolidadoAsignado,RangoUltimoBeneficioAsignado,FechaUltimoBeneficioAsignado,RangoEdad,Titular,CantidadDeBeneficiarios
0,SI,8,8421,NO,ACTIVO,AFROCOLOMBIANO – NEGRO,2012-12-01,Hombre,ND,ATLANTICO,...,MONETARIO,ND,CC,UNIDOS,4.500.001 - 6.000.000,0 - 1.300.000,2018-01-01,30-49,SI,1
1,NO,13,13673,NO,NO ACTIVO,ND,2012-11-01,Mujer,ND,BOLIVAR,...,ND,ND,TI,ND,0 - 1.500.000,0 - 1.300.000,1900-01-01,18-29,NO,21
2,SI,8,8421,NO,ACTIVO,AFROCOLOMBIANO – NEGRO,2012-12-01,Hombre,ND,ATLANTICO,...,MONETARIO,ND,CC,UNIDOS,4.500.001 - 6.000.000,0 - 1.300.000,2018-01-01,30-49,SI,1
3,SI,8,8421,NO,ACTIVO,AFROCOLOMBIANO – NEGRO,2012-12-01,Hombre,ND,ATLANTICO,...,MONETARIO,ND,CC,UNIDOS,4.500.001 - 6.000.000,0 - 1.300.000,2018-01-01,30-49,SI,1
4,SI,8,8421,NO,ACTIVO,AFROCOLOMBIANO – NEGRO,2012-12-01,Hombre,ND,ATLANTICO,...,MONETARIO,ND,CC,UNIDOS,4.500.001 - 6.000.000,0 - 1.300.000,2018-01-01,30-49,SI,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3958589,NO,47,47675,NO,ACTIVO,ND,2016-01-01,Mujer,ND,MAGDALENA,...,MONETARIO,NUTRICIÓN,CC,DESPLAZADOS,1.500.001 - 3.000.000,0 - 1.300.000,2018-01-01,30-49,SI,1
3958590,NO,13,13442,NO,ACTIVO,ND,2014-04-01,Hombre,SECUNDARIA,BOLIVAR,...,ND,EDUCACIÓN SECUNDARIA,TI,DESPLAZADOS,0 - 1.500.000,0 - 1.300.000,1900-01-01,18-29,NO,7
3958591,NO,25,25875,NO,ACTIVO,ND,2012-10-01,Hombre,ND,CUNDINAMARCA,...,ND,ND,RC,SISBEN,0 - 1.500.000,0 - 1.300.000,1900-01-01,18-29,NO,2
3958592,NO,19,19807,NO,ACTIVO,ND,2017-07-01,Hombre,ND,CAUCA,...,ND,ND,TI,SISBEN,0 - 1.500.000,0 - 1.300.000,1900-01-01,18-29,NO,1
3958593,NO,88,88001,NO,ACTIVO,ND,2013-10-01,Hombre,SECUNDARIA,SAN ANDRES,...,ND,EDUCACIÓN SECUNDARIA,TI,SISBEN,0 - 1.500.000,0 - 1.300.000,1900-01-01,06-17,NO,4

Eliminacion de columnas innecesarias o con datos muy poco utiles y repetitivos

Columnas eliminadas: CodigoDepartamentoAtencion, Etnia, Genero, RangoUltimoBeneficioAsignado, CantidadDeBeneficiarios

In [4]:
Columnas_Eliminar=[
                    "CodigoDepartamentoAtencion",
                    "Etnia",
                    "Genero",
                    "RangoUltimoBeneficioAsignado",
                    "CantidadDeBeneficiarios"
                ]

try:
    df_Familias_En_Accion = df_Familias_En_Accion.drop(columns=Columnas_Eliminar)
    print("Las columnas seleccionadas se eliminaron con éxito")
except KeyError as e:
    print("Error al aliminar columnas: ",e)

Las columnas seleccionadas se eliminaron con éxito

In [3]:
df_Familias_En_Accion

,Bancarizado,CodigoMunicipioAtencion,Discapacidad,EstadoBeneficiario,FechaInscripcionBeneficiario,NivelEscolaridad,NombreDepartamentoAtencion,NombreMunicipioAtencion,Pais,TipoAsignacionBeneficio,TipoBeneficio,TipoDocumento,TipoPoblacion,RangoBeneficioConsolidadoAsignado,FechaUltimoBeneficioAsignado,RangoEdad,Titular
0,SI,8421,NO,ACTIVO,2012-12-01,ND,ATLANTICO,LURUACO,ND,MONETARIO,ND,CC,UNIDOS,4.500.001 - 6.000.000,2018-01-01,30-49,SI
1,NO,13673,NO,NO ACTIVO,2012-11-01,ND,BOLIVAR,SANTA CATALINA,ND,ND,ND,TI,ND,0 - 1.500.000,1900-01-01,18-29,NO
2,SI,8421,NO,ACTIVO,2012-12-01,ND,ATLANTICO,LURUACO,ND,MONETARIO,ND,CC,UNIDOS,4.500.001 - 6.000.000,2018-01-01,30-49,SI
3,SI,8421,NO,ACTIVO,2012-12-01,ND,ATLANTICO,LURUACO,ND,MONETARIO,ND,CC,UNIDOS,4.500.001 - 6.000.000,2018-01-01,30-49,SI
4,SI,8421,NO,ACTIVO,2012-12-01,ND,ATLANTICO,LURUACO,ND,MONETARIO,ND,CC,UNIDOS,4.500.001 - 6.000.000,2018-01-01,30-49,SI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3958589,NO,47675,NO,ACTIVO,2016-01-01,ND,MAGDALENA,SALAMINA,ND,MONETARIO,NUTRICIÓN,CC,DESPLAZADOS,1.500.001 - 3.000.000,2018-01-01,30-49,SI
3958590,NO,13442,NO,ACTIVO,2014-04-01,SECUNDARIA,BOLIVAR,MARIA LA BAJA,ND,ND,EDUCACIÓN SECUNDARIA,TI,DESPLAZADOS,0 - 1.500.000,1900-01-01,18-29,NO
3958591,NO,25875,NO,ACTIVO,2012-10-01,ND,CUNDINAMARCA,VILLETA,ND,ND,ND,RC,SISBEN,0 - 1.500.000,1900-01-01,18-29,NO
3958592,NO,19807,NO,ACTIVO,2017-07-01,ND,CAUCA,TIMBIO,Colombia,ND,ND,TI,SISBEN,0 - 1.500.000,1900-01-01,18-29,NO
3958593,NO,88001,NO,ACTIVO,2013-10-01,SECUNDARIA,SAN ANDRES,SAN ANDRES,ND,ND,EDUCACIÓN SECUNDARIA,TI,SISBEN,0 - 1.500.000,1900-01-01,06-17,NO